# Generated by Django 5.1.6 on 2025-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, db_comment="用户昵称", max_length=256, null=True
                    ),
                ),
                (
                    "user_account",
                    models.CharField(
                        blank=True, db_comment="账号", max_length=256, null=True
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(
                        blank=True, db_comment="用户头像", max_length=1024, null=True
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(blank=True, db_comment="性别", null=True),
                ),
                ("user_password", models.CharField(db_comment="密码", max_length=512)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_comment="电话", max_length=128, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_comment="邮箱", max_length=512, null=True
                    ),
                ),
                ("user_status", models.IntegerField(db_comment="状态 0-正常")),
                (
                    "create_time",
                    models.DateTimeField(blank=True, db_comment="创建时间", null=True),
                ),
                (
                    "update_time",
                    models.DateTimeField(blank=True, db_comment="更新时间", null=True),
                ),
                ("is_delete", models.IntegerField(db_comment="是否删除")),
                (
                    "user_role",
                    models.IntegerField(db_comment="用户角色 0-普通用户 1-管理员"),
                ),
                (
                    "planet_code",
                    models.CharField(
                        blank=True, db_comment="星球编号", max_length=512, null=True
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, db_comment="标签列表", max_length=1024, null=True
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "db_table_comment": "用户",
                "managed": False,
            },
        ),
    ]
