# Generated by Django 5.1.6 on 2025-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_comment="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        blank=True,
                        db_comment="标签名称",
                        max_length=256,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(blank=True, db_comment="用户id", null=True),
                ),
                (
                    "parent_id",
                    models.BigIntegerField(
                        blank=True, db_comment="父标签id", null=True
                    ),
                ),
                (
                    "is_parent",
                    models.IntegerField(
                        blank=True, db_comment="0-不是，1-父标签", null=True
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(blank=True, db_comment="创建时间", null=True),
                ),
                (
                    "update_time",
                    models.DateTimeField(blank=True, db_comment="更新时间", null=True),
                ),
                ("is_delete", models.IntegerField(db_comment="是否删除")),
            ],
            options={
                "db_table": "tags",
                "db_table_comment": "标签",
                "managed": False,
            },
        ),
    ]
